server {
    listen 80;
    listen [::]:80;
    server_name openvibe.community www.openvibe.community;
    return 301 https://openvibe.community$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name openvibe.community www.openvibe.community;

    ssl_certificate     /etc/letsencrypt/live/openvibe.community/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/openvibe.community/privkey.pem;

    root /opt/openvibe.community/public;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
