'use strict';

/**
 * /pulse — what is happening across the OpenVibe network, newest first, from Pulse
 * (server/pulse). Filtering by origin and paging ("Older") are links, so it works without
 * JavaScript. AI items carry an AI label and no person; system items name no one either.
 */
const seo = require('../seo');
const { renderPage } = require('./layout');
const { escapeHtml: esc } = require('./highlight');
const { timeTag } = require('./pages');
const { who } = require('./forum');

const FILTERS = [['', 'Everything'], ['user', 'People'], ['ai', 'AI'], ['system', 'System']];
const SERVICE_NAMES = { community: 'Community', live: 'Live', media: 'Media', network: 'Network', tools: 'Tools', games: 'Games', wiki: 'Wiki', blog: 'Blog', reviews: 'Reviews' };

const href = (origin, after) => {
    const q = new URLSearchParams();
    if (origin) q.set('origin', origin);
    if (after) q.set('after', after);
    const s = q.toString();
    return `/pulse${s ? `?${s}` : ''}`;
};

function itemHtml(it) {
    const service = SERVICE_NAMES[it.source.service] || it.source.service;
    const local = it.source.service === 'community';
    const byline = it.origin === 'ai'
        ? '<span class="badge badge-ai" title="Generated by AI — not written by a person">AI</span>'
        : it.origin === 'system' ? '<span class="badge">System</span>'
            : it.actor ? who(it.actor) : '<span class="muted">Anonymous</span>';
    return `<li class="pulse-item pulse-${esc(it.origin)}">
    <span class="badge pulse-source" title="${esc(`${it.source.service} · ${it.source.type}`)}">${esc(service)} · ${esc(it.source.type)}</span>
    <div class="pulse-main">
      <a class="thread-title" href="${esc(it.url)}"${local ? '' : ' rel="nofollow ugc noopener"'}>${esc(it.title)}</a>
      <p class="thread-meta">${byline} <span class="sep">·</span> ${timeTag(it.occurred_at)}</p>
    </div>
  </li>`;
}

function pulsePage({ items, origin = '', after = null, nextCursor = null }) {
    const tabs = FILTERS.map(([id, label]) => `<a class="tab${id === origin ? ' active' : ''}" href="${esc(href(id))}"${id === origin ? ' aria-current="page"' : ''}>${label}</a>`).join('');
    const body = `
<header class="page-head">
  <nav class="crumbs" aria-label="Breadcrumb"><a href="/">Home</a> › <span aria-current="page">Pulse</span></nav>
  <h1>Pulse</h1>
  <p class="muted">Public activity from across OpenVibe as it happens: new pastes, threads and replies here, and what the other sites share. Only public things appear, and anything made by AI is labelled as AI.</p>
</header>
<nav class="tabs sort-tabs" aria-label="Filter by origin">${tabs}</nav>
<section data-results${after ? '' : ' data-pulse-live'}>
  <p class="pulse-new" hidden><button type="button" class="btn btn-sm" data-pulse-show></button></p>
  ${items.length ? `<ol class="thread-list pulse-list">${items.map(itemHtml).join('')}</ol>` : '<p class="empty">Nothing here yet.</p>'}
  ${after || nextCursor ? `<nav class="pager" aria-label="Pages">${after ? `<a href="${esc(href(origin))}"><i class="fa-solid fa-chevron-left" aria-hidden="true"></i> Latest</a>` : '<span></span>'}<span></span>${nextCursor ? `<a rel="next" href="${esc(href(origin, nextCursor))}">Older <i class="fa-solid fa-chevron-right" aria-hidden="true"></i></a>` : '<span></span>'}</nav>` : ''}
</section>`;
    return renderPage({
        title: `Pulse${origin ? ` — ${FILTERS.find(([id]) => id === origin)[1]}` : ''}`,
        description: 'The pulse of the OpenVibe network: new public pastes, threads, replies and what the other OpenVibe sites share, with AI-made items labelled as AI.',
        canonicalPath: href(origin, after),
        // The first page of each filter is worth indexing; deep cursors are not.
        robots: after ? 'noindex,follow' : 'index,follow',
        active: 'pulse',
        feeds: [{ title: 'OpenVibe.Community — latest threads', href: '/s/feed.xml' }],
        jsonLd: [seo.breadcrumbLd([{ name: 'Home', url: '/' }, { name: 'Pulse', url: '/pulse' }])],
        body,
    });
}

module.exports = { pulsePage };
